### ISSUE TITLE
Lack of documentation - configuration without annotation 

### ISSUE THREAD

**Issue by saganov** [api-platform/docs#1025]
There are no documentation of how to configure entities without pollution of code with an annotation - just with a config files `config/api_platform/resources.yaml`

**Comment by dunglas** [comment]
Any help to improve this is very welcome (it's easy to guess the XML or YAML structure from the annotation)

**Comment by smilesrg** [comment]
Can't find how to use `api/config/api_platform/resources.yaml`

**Comment by smilesrg** [comment]
Mappings to `config/packages/api_platform.yaml` should be added.

https://api-platform.com/docs/core/getting-started/#product

```yaml
# api/config/packages/api_platform.yaml
api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
```

It's a good idea to mention it in the provided examples.
