### ISSUE TITLE
Docs cannot access JWT secured API , Authorization header misses Bearer

### ISSUE THREAD

**Issue by michael-schaefer-eu** [api-platform/docs#1087]
## Summary

After I implemented the JWT security package, the Docs cannot access the resources anymore, because they generate an invalid curl command that misses the "Bearer" in the Authorization header.
 
## System

- latest API Platform Distribution (v2.5.4)
- lexik/jwt-authentication-bundle v2.6

`secure.yaml`
```yaml
security:
    encoders:
        App\Entity\User\ClientUser:
            algorithm: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\ClientUser
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            stateless: true
            anonymous: true
            provider: app_user_provider
            
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

## Steps to reproduce

I add a user to the DB with email and encoded password (both _admin@example.com_ and create a JWT via curl:

```
curl --insecure -X POST "https://localhost:8443/login" -H "accept: application/ld+json" -H "Content-Type: application/ld+json" -d "{ \"email\": \"admin@example.com\", \"password\": \"admin@example.com\"}"
```
and get the response with a valid token:
```
{"token":"eyJ0eXAiOiJ.....lvIn0.ah_m8k"}
```
now I test that the token is really OK
```
curl --insecure -X GET "https://localhost:8443/addresses?page=1" -H  "accept: application/ld+json" -H  "Authorization: Bearer eyJ0eXAiOiJ.....lvIn0.ah_m8k"
```
and get again a valid JSON+LD response 
```json
{
    "@context":"\/contexts\/Address",
    "@id":"\/addresses",
    "@type":"hydra:Collection",
    "hydra:member": [{
        "@id": "\/addresses\/472e48e9-5688-43f8-a17c-af2fb9c2ef3b",
        "@type": "Address",
...
        "country": "Germany",
        "type": "headquarter",
        "company": "\/companies\/0b410438-d7c7-4db1-be64-bc180f2e1b6e"
    }, {
        "@id": "\/addresses\/60c77c73-6412-4995-8114-5277541db7f9",
        "@type": "Address",
        "country": "France",
...
        "type": "headquarter",
        "company": "\/companies\/06963e66-be12-45df-b071-64c278fe03c0"
    }, {
        "@id": "\/addresses\/ac9a5d4b-dff4-44bf-9953-1fe36f31713b",
        "@type": "Address",
        "country": "Great Britain",
...
        "type": "headquarter",
        "company": "\/companies\/62e0122a-ca6a-48ba-b597-9fca9fdf446c"
    }],
    "hydra:totalItems":3
}
```

## Problem

I open the https://localhost:8443/docs , click on the `Authorize` Button and insert the Token.

Now I try to execute same request as above, but get an error response
```json
{
  "code": 401,
  "message": "JWT Token not found"
}
```

![Bildschirmfoto von 2020-04-03 22-51-35](https://user-images.githubusercontent.com/9930093/78404031-dd685780-75fd-11ea-8e4d-203ea57b287c.png)

The curl command is this:
```
curl -X GET "https://localhost:8443/addresses?page=1" -H  "accept: application/ld+json" -H  "Authorization: eyJ0eXAiOiJ.....lvIn0.ah_m8k"
```
It misses the "Bearer" in the Authorization header.
