### ISSUE TITLE
How to make GraphQL Interface work

### ISSUE THREAD

**Issue by oleg-brizy** [api-platform/docs#1139]
_(for those who will struggle with this problem and will search in issues)_

1. Register your interface and implementation types
2. Use interface on some entity field (via [decorated type converter](https://api-platform.com/docs/core/graphql/#modify-the-extracted-types))
3. Make your implementation types visible in schema by adding them in schemaConfig.types (via decorated schema builder)

```yaml
services:
    App\Type\GraphQL\SchemaBuilder:
        decorates: api_platform.graphql.schema_builder
```

```php
<?php

namespace App\Type\GraphQL;

use ApiPlatform\Core\GraphQl\Type\SchemaBuilder as DecoratedSchemaBuilder;
use ApiPlatform\Core\GraphQl\Type\SchemaBuilderInterface;
use ApiPlatform\Core\GraphQl\Type\TypesContainerInterface;
use GraphQL\Type\Schema;

class SchemaBuilder implements SchemaBuilderInterface
{
    private DecoratedSchemaBuilder $decorated;
    private TypesContainerInterface $typesContainer;

    public function __construct(
        DecoratedSchemaBuilder $decorated,
        TypesContainerInterface $typesContainer
    )
    {
        $this->decorated = $decorated;
        $this->typesContainer = $typesContainer;
    }

    public function getSchema(): Schema
    {
        $config = $this->decorated->getSchema()->getConfig();

        /**
         * Make interfaces work
         * https://github.com/webonyx/graphql-php/issues/99#issuecomment-287439086
         */
        $config->setTypes([
            $this->typesContainer->get('InterfaceImplementationFoo'),
            $this->typesContainer->get('InterfaceImplementationBar'),
            $this->typesContainer->get('InterfaceImplementationBaz'),
        ]);

        return new Schema($config);
    }
}
```

**Comment by oleg-brizy** [comment]
4. If you overwrite entity type to your custom interface type (via type converter) then you will get `id` fields without IRI
  (`"23"` instead of `"/entity_name/23"`)

    The fix is to provide `$config['resolveField'] = $resolver` in interface implementation `ObjectType` definition.

    1. Use this service as resolver

        ```yaml
        App\Type\GraphQL\MyInterfaceImplementationOrBuilder:
            arguments:
                $defaultFieldResolver: '@api_platform.graphql.resolver.resource_field'
        ```

    2. In object definition

        ```php
        use ApiPlatform\Core\GraphQl\Resolver\ResourceFieldResolver;

        ...

        public function __construct(ResourceFieldResolver $defaultFieldResolver) {
            $this->defaultFieldResolver = $defaultFieldResolver;
        }

        ...

        // https://webonyx.github.io/graphql-php/type-system/interfaces/#implementing-interface
        $config['interfaces'] = [ $interface ];
        $config['resolveField'] = $this->defaultFieldResolver; // fixes {id: "7"} to {"id": "/my_type/7"}
        ```
