### ISSUE TITLE
Update doc in yaml configuration for custom filter

### ISSUE THREAD

**Issue by abdounikarim** [api-platform/docs#1211]
Hello,

I'm using yaml configuration for filter and i don't see anywhere in the docs how to type the `properties` attributes.
Can you add an example for this configuration ?

Thanks.

**Comment by soyuka** [comment]
https://github.com/api-platform/docs/issues/1039#issuecomment-723122559 may help?

**Comment by abdounikarim** [comment]
@soyuka found it, i paste an exemple if someone need a configuration : 
```yaml
app.book.search.filter:
        class: App\Filter\BookSearchFilter
        parent: "api_platform.doctrine.orm.search_filter"
        arguments:
            $properties: { 'search': ~ }
        tags:
            - { name: "api_platform.filter", id: 'book.search.filter' }
```
