### ISSUE TITLE
GraphQL File Upload documentation causes error

### ISSUE THREAD

**Issue by brettins** [api-platform/docs#1361]
When implemented according to the documentation here: 

https://api-platform.com/docs/core/graphql/#using-the-createmediaobject-mutation

```
# api/config/packages/api_platform.yaml
api_platform:
    formats:
        # ...
        multipart: ['multipart/form-data']
```

The platform returns an error: 

```
The routing file "/srv/api/config/routes/api_platform.yaml" contains unsupported keys for "api_platform": "formats". Expected one of: "resource", "type", "prefix", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition", "controller", "name_prefix", "trailing_slash_on_root", "locale", "format", "utf8", "exclude", "stateless" in /srv/api/config/routes/api_platform.yaml (which is being imported from "/srv/api/src/Kernel.php").
```

Changing the `formats` to `format` in that list gives the error: 

```
Illegal offset type in isset or empty
```
