### ISSUE TITLE
Circular reference detected for service "App\OpenApi\JwtDecorator"

### ISSUE THREAD

**Issue by kochen** [api-platform/docs#1418]
Current documentation causes a circular reference for the decorated service.

A special `.inner` value was introduced in `Symfony 5.1`:
```
# config/services.yaml
services:
    App\Mailer: ~

    App\DecoratingMailer:
        decorates: App\Mailer
        # pass the old service as an argument
        arguments: ['@.inner']
```
See: https://symfony.com/blog/new-in-symfony-5-1-simpler-service-decoration
