### ISSUE TITLE
[2.7] Decorated Processor docs seem wrong

### ISSUE THREAD

**Issue by KDederichs** [api-platform/docs#1568]
In https://api-platform.com/docs/main/core/state-processors/ it says that you need to decorate the processor like this:
```
services:
    # ...
    App\State\UserProcessor:
        bind:
            $decorated: '@api_platform.doctrine.orm.state_processor'
```
 but the `@api_platform.doctrine.orm.state_processor` doesn't seem to exist.

What does work though is injecting the `@ApiPlatform\Doctrine\Common\State\PersistProcessor` or `@ApiPlatform\Doctrine\Common\State\RemoveProcessor` directly though. Is that intended? 
If so it should be reflected in the Docs.

**Comment by alanpoulain** [comment]
New way of doing it:
```yaml
services:
    App\Processor\FooProcessor:
        bind:
             $decorated: '@api_platform.doctrine.orm.state.persist_processor'
```

To use it, please use `dev-main` version of API Platform, while waiting for a new release.
