### ISSUE TITLE
Pagination for specific resource is missing YAML documentation.

### ISSUE THREAD

**Issue by catalin87** [api-platform/docs#1671]
Hello,

I`m using api-platform/core:3.0.6

We upgraded from api platform 2.4 to 3.0.6.

Everything seems to work except pagination.
We not using annotations at all so I try to configure using YAML file.

The problem is that in the documentation ( [Disabling the Pagination For a Specific Resource](https://api-platform.com/docs/v2.7/core/pagination/#disabling-the-pagination-for-a-specific-resource) )
we only have annotations example.

I want to disable pagination and show all the results for my Region entity, while the pagination remains active fore any other entity.

I try everything and is not working with YAML.

Actual configs:
```
resources.yml (Ressource deffinition)

    CommonBundle\Entity\Region:
        shortName: 'Region'
        description: 'Region'
        normalizationContext:
            groups: [ 'region_read' ]
        denormalizationContext:
            groups: [ 'region_write' ]
        operations:
            ApiPlatform\Metadata\GetCollection:
                filters:
                    - region.search
                    - region.order
            ApiPlatform\Metadata\Get:
                filters:
                    - region.search
                    - region.order
```

```
region.yml (serialization groups definitions):

DomainBundle\Entity\Region:
    attributes:
        id:
            groups: ['region_read', 'good_read', 'customer_read']
        name:
            groups: ['region_read', 'region_write', 'good_read']
        abbreviation:
            groups: ['region_read', 'region_write']
        localities:
            groups: ~
```

```
config.yml:

api_platform:
    defaults:
        force_eager: true
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_client_partial: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 1000
        pagination_partial: false
```

I try to disable resources.yml and use the anotations, and all is working, but we cannot use annotations at all.
```
Region.php:

#[ApiResource(paginationEnabled: false)]
class Region
{
```

So where I need to put `pagination_enabled: false` inside the .yml files?
I tried all the ways but without success, and the official documentation is missing this aspect.

Thanks in advance for any help!
