### ISSUE TITLE
How to properly setup yaml serialization

### ISSUE THREAD

**Issue by CpHeat** [api-platform/docs#1842]
I don't know if it's the documentation or me but I can't find how to make serialization work using yaml files

Here's what I have :

#config/api_platform/resources/Game.yaml
```
resources:
  App\Entity\Game:
    attributes:
      normalizationContext:
        groups: [ 'read' ]
      denormalizationContext:
        groups: [ 'write' ]
```

#config/api_platform/serializer/Game.yaml
```
App\Entity\Game:
  attributes:
    name:
      groups: ['read']
    id:
      groups: ['write']
    boxes:
      groups: ['write']
```

#config/packages/framework.yaml
```
framework:
    serializer:
        mapping:
            paths: [ '%kernel.project_dir%/config/api_platform/serializer/Game.yaml' ]
```

#config/packages/api_platform.yaml
```
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources/Game.yaml']
```
        
I searched a lot and tried different things but it doesn't work, I get name, id and boxes in every request I make. If I use the annotations inside the Entity file it works just fine

I hope someone can help me in telling me what I'm doing wrong ?

Thanks !

EDIT : My bad there should be no attributes line in the resources file I'm closing this issue
