### ISSUE TITLE
Docs on pagination in subresources

### ISSUE THREAD

**Issue by RonRademaker** [api-platform/docs#453]
Hi,

I'm using a subresource and everything works, except that the page parameter just won't document itself in the api-platform interface or the docs.json. My configuration looks like:

``` yml
    My\Model\Entity\Foo:
        description: 'Fetch foo data'
        collectionOperations: []
        properties:
            bars:
                subresource:
                    resourceClass: 'My\Model\Entity\Bar'
                    collectionOperations:
                        get:
                            method: 'GET'
        itemOperations:
            get:
                method: 'GET'
        attributes:
            normalization_context:
                groups: ['foo']
    My\Model\Entity\Bar:
        description: 'Fetch bar data'
        collectionOperations: []
        itemOperations:
            get:
                method: 'GET'
        attributes:
            pagination_enabled: true
            pagination_items_per_page: 6
            pagination_page_parameter_name: 'page'
            normalization_context:
               groups: ['bar']
```

The page parameter works if I add it to a method call manually, but I need my api client to know about the parameter as well. How do I do this?
