### ISSUE TITLE
Unable to change the Swagger UI Location

### ISSUE THREAD

**Issue by comxd** [api-platform/docs#458]
@see https://github.com/api-platform/api-platform/issues/635

About the api-platform documentation at: _Changing the Swagger UI Location_

I got this error for "/" and "/docs" routes:
Serialization for the format html is not supported.

```
#api/config/routes.yaml
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
```

```
# api/config/packages/api_platform.yaml
api_platform:
    # ...
    enable_swagger_ui: false
```

It's due to the route `vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/config/routing/docs.xml : /docs.{_format}` used for the hydra doc.

For change the Swagger UI location, we need to : 
* Override the `/docs.{_format}` route
* or Choose another location of "/docs"
