### ISSUE TITLE
Missing doc about how to change base path of ApiPlatform

### ISSUE THREAD

**Issue by Nek-** [api-platform/docs#464]
Hello,

In my apps I change the base path of ApiPlatform by using something similar to that:
```yaml
# routing/api_platform.yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /v1

api:
    resource: ../api_platform/routes/api.yaml
    prefix:   /v1
```

But I can't find something about in the documentation. Was it removed? Or is it just missing?
