### ISSUE TITLE
Identifier date doctrine type converts to value with time that broke item query result

### ISSUE THREAD

**Issue by Simperfit** [api-platform/docs#465]
from: https://github.com/api-platform/core/issues/1233
We had the same issue and I think that #1478 is a slightly better fix, indeed it allows you to add a normalizer for any identifer (uuid or datetime), for example:

```php
<?php
// DateIdentifierNormalizer

namespace Core\ApiBundle\Identifier\Normalizer;
use AppBundle\Orm\Types\IdxDate; // using a custom Doctrine Type here

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

class DateNormalizer implements DenormalizerInterface
{
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return (string) (new IdxDate($data));
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === IdxDate::class;
    }
}
```

```yaml
services:
    bender_api.date_identifier_normalizer:
        public: false
        class: Core\ApiBundle\Identifier\Normalizer\DateNormalizer
        tags: [ { name: 'api_platform.identifier_normalizer' } ]
```

```php
<?php
namespace AppBundle\Orm\Types;

class IdxDate extends \DateTime
{
    public function __toString()
    {
        return $this->format('d-m-Y');
    }

    public static function createFromFormat($format, $time, $object = null)
    {
        $d = \DateTime::createFromFormat($format, $time);

        $t = new self();
        $t->setTimestamp($d->getTimeStamp());

        return $t;
    }
}
```

Keeping this here for docs
