### ISSUE TITLE
Incorrect syntax of SwaggerUI

### ISSUE THREAD

**Issue by borNfreee** [api-platform/docs#555]
https://api-platform.com/docs/core/swagger#changing-operations-in-the-swagger-documentation

This example uses old syntax of SwaggerUI v1 - `requestBody`, which does not work in SwaggerUI v2.

You can check it in online editor: https://editor.swagger.io/

The correct syntax for this example would be:

```yaml
resources:
  App\Entity\Rabbit:
    collectionOperations:
      create_user:
        method: get
        path: '/rabbit/rand'
        controller: App\Controller\RandomRabbit
        swagger_context:
          summary: Random rabbit picture
          description: >
            # Pop a great rabbit picture by color!

            ![A great rabbit](https://rabbit.org/graphics/fun/netbunnies/jellybean1-brennan1.jpg)

          parameters:
            -
               in: body
               schema:
                   type: object
                   properties:
                       name: {type: string}
                       description: {type: string}
               example:
                   name: Rabbit
                   description: Pink rabbit

```
