### ISSUE TITLE
[RFC] Add mention how to disable force-eager and that it will mess up any complex queries

### ISSUE THREAD

**Issue by diimpp** [api-platform/docs#623]
Hi,

I was doing custom `Filter` for my current project and just spent like 5 hours debugging empty result for my query, which was result of `api-platform/core/src/Bridge/Doctrine/Orm/Extension/FilterEagerLoadingExtension.php` wrapping part of my query with `IN` operator.

I was using `groupBy`, `having` with `where in` query together, which got disrupted as part with `where` was moved into sub-select.

Next configuration example solved my problem fully.

```yaml
Acme\Entity\Entity:
    collectionOperations:
        get:
            force_eager: false
```

Thanks.
