### ISSUE TITLE
Service definition for 'Overriding OpenAPI Specification' is wrong

### ISSUE THREAD

**Issue by jmwri** [api-platform/docs#726]
On the page https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification the example service definition is as follows:

```
# api/config/services.yaml
services:
    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
```

This used to work, although it seems a new service has been added:

```
<service id="api_platform.swagger.normalizer.api_gateway" class="ApiPlatform\Core\Swagger\Serializer\ApiGatewayNormalizer" public="false" decorates="api_platform.swagger.normalizer.documentation">
    <argument type="service" id="api_platform.swagger.normalizer.api_gateway.inner" />
    <tag name="serializer.normalizer" priority="17" />
</service>
```

This service now takes precedence over the custom `SwaggerDecorator`. The correct service definition should be:

```
# api/config/services.yaml
services:
    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.api_gateway'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
```

Was this change mentioned anywhere?
