### ISSUE TITLE
Default configuration is wrong

### ISSUE THREAD

**Issue by auipga** [api-platform/docs#807]
If the values provided as default (see [2.4/core/configuration.md](https://github.com/api-platform/docs/blob/2.4/core/configuration.md)) really are the defaults, then I expect them to work.

The following defaults don't work:
```yaml
api_platform:
    title: ''                         # cannot contain an empty value
    description: ''                   # cannot contain an empty value
    collection:
        pagination:
            maximum_items_per_page: ~ # Expected int, but got NULL
    http_cache:
        max_age: ~                    # Expected int, but got NULL
        shared_max_age: ~             # Expected int, but got NULL
```
