### ISSUE TITLE
Mention complex access_control scenario

### ISSUE THREAD

**Issue by ro0NL** [api-platform/docs#983]
We have a dedicated project hosting our API, the routing is mounted at root level. So `/endpoints`, and not `/api/endpoints`, respecitvely;

```yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /
```

I soon realized this comes with a cost for security configuration, due the lack of a shared prefix to capture / match against.

Our use case; a closed API, but allow the swagger UI in dev without authentication.

I crafted this piece of configuration, which perhaps is good to share/mention for future reference somewhere. Feel free to close as well :)

```yaml
security:
    access_control:
        # closed API, but allow swagger UI/HTML in "dev"
        # security runs before routing, so we don't know the controller nor request format
        # hence we check Accept header, and assume all HTML is documentation
        -
            path: ^/
            roles: IS_AUTHENTICATED_FULLY
            allow_if: "'%kernel.environment%' == 'dev' and 'text/html' in request.getAcceptableContentTypes()"
```

Let me know if it can be optimized / there's a better approach.
